// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zalsfqixapzrpwhbafpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphbHNmcWl4YXB6cnB3aGJhZnBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxMDk2MjAsImV4cCI6MjA3NzY4NTYyMH0.ykiA6lFNKASTovTOXkVjYjqHwbVan7YNvZPD4TRpPsI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});